classmate/urls.py
from django.conf.urls import *
from zhyserver.settings import *
from django.conf.urls.static import static
urlpatterns = patterns('classmate.views',
    url(r'^$', 'index'),
    url(r'^index/', 'index'),
    url(r'^test/', 'test'),
    url(r'^weixin/', 'weixin'),
    url(r'^album/', 'album'),
    url(r'^sms/', 'sms'),
    url(r'^bye/', 'bye'),

    url(r'^createclass/', 'create_class'),
    url(r'^changeclass/(\d+)/$', 'change_class'),
    url(r'^enterclass/(\d+)/$', 'enter_class'),

    url(r'^createstudent/(\d+)/$', 'create_student'),
    url(r'^changestudent/(\d+)/$', 'change_student'),
) + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += patterns('classmate.ajax',
    url(r'^ajax/queryclass/', 'query_class'),
    url(r'^ajax/createclass/', 'create_class'),
    url(r'^ajax/querycollege/', 'query_college'),
    url(r'^ajax/querydepartment/', 'query_department'),
    url(r'^ajax/querylogin/', 'query_login'),
    url(r'^ajax/upload/(\d+)/$', 'upload'),
    
    url(r'^ajax/queryalbum/', 'query_album'),
)

urlpatterns += patterns('classmate.interface',
    url(r'^interface/validate/', 'validate'),
)

zhyserver/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('classmate.urls')),
    # Examples:
    # url(r'^$', 'zhyserver.views.home', name='home'),
    # url(r'^zhyserver/', include('zhyserver.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

classmate/forms.py
#-*- coding: utf-8 -*-
from django import forms
from models import *
import re

class RegisterForm(forms.Form):
    college    = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'点我选择','readonly':'readonly','style':'background-color:white'}),required=True)
    department = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'点我选择','readonly':'readonly','style':'background-color:white'}),required=True)
    classnum   = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'4~20个数字'}),required=True, min_length=4, max_length=20)
    year       = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'示例: 2012'}),required=True)
    slogon  = forms.CharField(widget=forms.TextInput(attrs={'class':'span12'}),required=False)

    studentnum  = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'4~20个数字'}),required=True, min_length=4, max_length=20)
    name        = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'1~6个数字'}),required=True, min_length=1, max_length=6)
    qq          = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'7~20个数字'}),min_length=7, max_length=20,required=False)
    weibo       = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'7~20个数字'}),min_length=7, max_length=20,required=False)
    mail        = forms.EmailField(widget=forms.TextInput(attrs={'class':'span12'}),required=False)
    phone       = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'4~12个数字'}),min_length=4, max_length=12,required=False)
    birthday    = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'点我选择','readonly':'readonly','style':'background-color:white'}),required=False)
    position    = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'点我选择','readonly':'readonly','style':'background-color:white'}),required=True)
    weixin      = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'OpenID不是微信号, 是一串杂七杂八的字符'}),min_length=7, max_length=35,required=False)
    
    quest1  = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'示例: 我们班的美女?'}),required=True)
    quest2  = forms.CharField(widget=forms.TextInput(attrs={'class':'span12'}),required=True)
    quest3  = forms.CharField(widget=forms.TextInput(attrs={'class':'span12'}),required=True)
    answer1 = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'示例: 小龙女|黄蓉|林志玲'}),required=True)
    answer2 = forms.CharField(widget=forms.TextInput(attrs={'class':'span12'}),required=True)
    answer3 = forms.CharField(widget=forms.TextInput(attrs={'class':'span12'}),required=True)
    def clean_classnum(self):
        try:
            classnum = self.cleaned_data['classnum']
            int(classnum)
            depid = int(re.sub(r'[^0-9]','',self.cleaned_data['department']))
        except:
            raise forms.ValidationError("classnum field error!")   
        if 0 != len(Class.objects.filter(classnum=classnum, department=Department(depid=depid))):
            raise forms.ValidationError("该班级已经被注册")
        else: return classnum

    def clean_year(self):
        try:
            year = self.cleaned_data['year']
            int(year)
            if len(year) != 4:
                raise forms.ValidationError("year field error!")
            else:
                return year
        except:raise forms.ValidationError("year field error!")
    def clean_studentnum(self):
        try:
            studentnum = self.cleaned_data['studentnum']
            int(studentnum)
            return studentnum
        except:raise forms.ValidationError("studentnum field error!")
    def clean_birthday(self):
        try:
            birthday = self.cleaned_data['birthday']
            if birthday.strip() == '': return ''
            int(birthday[1:])
            if len(birthday) != 9 or birthday[0] not in ['g','n']:
                raise forms.ValidationError("birthday field error!")
            else:
                return birthday
        except:raise forms.ValidationError("birthday field error!")
    def clean_phone(self):
        try:
            phone = self.cleaned_data['phone']            
            if phone.strip() == '': return ''
            int(phone)
            return phone
        except:raise forms.ValidationError("phone field error!")
    def clean_qq(self):
        try:
            qq = self.cleaned_data['qq']          
            if qq.strip() == '': return ''
            int(qq)
            return qq
        except:raise forms.ValidationError("qq field error!")
    def clean_weibo(self):
        try:
            weibo = self.cleaned_data['weibo']        
            if weibo.strip() == '': return ''
            int(weibo)
            return weibo
        except:raise forms.ValidationError("weibo field error!")
class ValidateForm(forms.Form):
    answer1 = forms.CharField(required=True)
    answer2 = forms.CharField(required=True)
    answer3 = forms.CharField(required=True)

    def clean_answer1(self):
        try:
            answer1 = self.cleaned_data['answer1'].strip()
            if answer1 == '':
                raise forms.ValidationError("answer1 field error!")
            else:return answer1
        except:raise forms.ValidationError("answer1 field error!")
    def clean_answer2(self):
        try:
            answer2 = self.cleaned_data['answer2'].strip()
            if answer2 == '':
                raise forms.ValidationError("answer2 field error!")
            else:return answer2
        except:raise forms.ValidationError("answer2 field error!")
    def clean_answer3(self):
        try:
            answer3 = self.cleaned_data['answer3'].strip()
            if answer3 == '':
                raise forms.ValidationError("answer3 field error!")
            else:return answer3
        except:raise forms.ValidationError("answer3 field error!")

class StudentForm(forms.Form):
    studentnum  = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'4~20个数字'}),required=True, min_length=4, max_length=20)
    name        = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'1~6个数字'}),required=True, min_length=1, max_length=6)
    qq          = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'7~20个数字'}),min_length=7, max_length=20,required=False)
    weibo       = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'7~20个数字'}),min_length=7, max_length=20,required=False)
    mail        = forms.EmailField(widget=forms.TextInput(attrs={'class':'span12'}),required=False)
    phone       = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'4~12个数字'}),min_length=4, max_length=12,required=False)
    birthday    = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'点我选择','readonly':'readonly','style':'background-color:white'}),required=False)
    position    = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'点我选择','readonly':'readonly','style':'background-color:white'}),required=True)
    weixin      = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'OpenID不是微信号, 是一串杂七杂八的字符'}),min_length=7, max_length=35,required=False)
        
    def __init__(self, *args, **kwargs):
        self.classid = kwargs.pop('classid')
        super(StudentForm, self).__init__(*args, **kwargs)
    
    def clean_studentnum(self):
        try:
            studentnum = self.cleaned_data['studentnum']
            int(studentnum)
        except:
            raise forms.ValidationError("studentnum field error!")  
        if self.classid == None:
            return studentnum
        if 0 != len(Student.objects.filter(studentnum=studentnum, classs=Class(classid=self.classid))):
            raise forms.ValidationError("该学号已经被注册")
        else: return studentnum
        
    def clean_birthday(self):
        try:
            birthday = self.cleaned_data['birthday']
            if birthday.strip() == '': return ''
            int(birthday[1:])
            if len(birthday) != 9 or birthday[0] not in ['g','n']:
                raise forms.ValidationError("birthday field error!")
            else:
                return birthday
        except:raise forms.ValidationError("birthday field error!")
    def clean_phone(self):
        try:
            phone = self.cleaned_data['phone']            
            if phone.strip() == '': return ''
            int(phone)
            return phone
        except:raise forms.ValidationError("phone field error!")
    def clean_qq(self):
        try:
            qq = self.cleaned_data['qq']          
            if qq.strip() == '': return ''
            int(qq)
            return qq
        except:raise forms.ValidationError("qq field error!")
    def clean_weibo(self):
        try:
            weibo = self.cleaned_data['weibo']        
            if weibo.strip() == '': return ''
            int(weibo)
            return weibo
        except:raise forms.ValidationError("weibo field error!")

class ClassForm(forms.Form):
    slogon  = forms.CharField(widget=forms.TextInput(attrs={'class':'span12'}),required=False)
    quest1  = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'示例: 我们班的美女?'}),required=True)
    quest2  = forms.CharField(widget=forms.TextInput(attrs={'class':'span12'}),required=True)
    quest3  = forms.CharField(widget=forms.TextInput(attrs={'class':'span12'}),required=True)
    answer1 = forms.CharField(widget=forms.TextInput(attrs={'class':'span12','placeholder':u'示例: 小龙女|黄蓉|林志玲'}),required=True)
    answer2 = forms.CharField(widget=forms.TextInput(attrs={'class':'span12'}),required=True)

templates/album.html
{% extends "base.html" %}
{% block page %}
<!-- Input
================================================== -->
<div class="row-fluid">
    <div class="span2"></div>
    <div class="span8 text-center">
        <img src="http://bcs.duapp.com/mediaavatar/tongchuang2thunder.png"> 
        <br/>
        <a href="http://bcs.duapp.com/mediaavatar/AlbumDownloader-13.0716.1.zip">点我下载(当前版本13.0716.1, 需要.Net支持)</a>
    </div>
    <div class="span2"></div>
</div>
<hr class="soften">
<div class="row-fluid">
    <div class="row-fluid">
        <div class="span1"></div>
        <div class="span10 text-center">
            <img src="http://bcs.duapp.com/mediaavatar/tutorial.png"> 
            执行完以上步骤后, 选择导出迅雷下载链接即可。<br/>
            您可以将生成的QQAlbum.lst文件导入迅雷批量下载。
        </div>
        <div class="span1"></div>
    </div>
    <!--
    <div class="row-fluid">
        <div class="span4"></div>
        <div class="span4">
            <ul style="list-style-type:none;text-indent: 2em;">
            <li>1. 关注大学同窗微信：daxuetongchuang</li>
            <li>2. 发任何消息到大学同窗，获取OpenID</li>
            <li>3. 创建班级后添加成员，填写OpenID并提交</li>
            <li>4. 发送「帮助」可获取指令</li>
            </ul>
        </div>
        <div class="span4"></div>
    </div>-->
</div> 
{% endblock %}

templates/base.html
<!DOCTYPE html>
<!--  
Template Name: Conquer Responsive Admin Dashboard Template build with Twitter Bootstrap 2.3.1
Version: 1.4
Author: KeenThemes
Website: http://www.keenthemes.com
Purchase: http://themeforest.net/item/conquer-responsive-admin-dashboard-template/3716838
-->
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en" style="height:100%;width:100%;margin:auto 0px;"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
	<meta charset="utf-8" />
	<title>大学同窗 | 留住回忆 延续感动</title>
	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta content="" name="提供大学班级同学联系方式、地理位置等信息的查询服务。" />
	<meta content="" name="zhangxiaoyang" />
    <meta name="baidu-site-verification" content="kEnQHqPFbn" />
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" /> 
	<!-- BEGIN GLOBAL MANDATORY STYLES -->
	<link href="/static/css/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/static/css/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" /> 
    <link href="/static/css/bootstrap/css/docs.css" rel="stylesheet" />  
    <link href="/static/css/uploadify.css" rel="stylesheet" />     
    <link href="/static/css/jquery.Jcrop.min.css" rel="stylesheet" />  
    <link rel="stylesheet" href="http://api.map.baidu.com/library/SearchInfoWindow/1.5/src/SearchInfoWindow_min.css" />
    <link href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" rel="stylesheet" />    
    {% block css %}{% endblock %}
	<!-- END PAGE LEVEL STYLES -->
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body screen_capture_injected="true">
    <!-- Navbar
    ================================================== -->
  <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="brand" style="float:left" href="/index">大学同窗</a>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li class="active">
                            <a href="/index">主页</a>
                        </li>
                        <li class="active">
                            <a href="/weixin">微信版</a>
                        </li>
                        <li class="active">
                            <a href="/album">QQ相册批量导出</a>
                        </li>
                        <li class="active">
                            <a href="/sms">手机短信批量导出</a>
                        </li>
                    </ul>
                </div>
                <div class="nav-collapse collapse pull-right">
                    <ul class="nav">
                        <li class="dropdown-toggle">
                            {% if request.user.pk %}
                            <a href="#" id="current" class="dropdown-toggle" data-toggle="dropdown" style="display:none;">{{request.user.pk}}</a>
                            <ul class="dropdown-menu">
                                <li><a href="/enterclass/{{request.user.pk}}">我的家</a></li>
                                <li class="divider"></li>
                                <li><a href="/bye">退出登录</a></li>
                            </ul>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!-- container
    ================================================== -->
    <div class="container">
	{% block page %}{% endblock %}
    </div>
    <!-- blank
    ================================================== -->
    <footer class="footer">
        <div class="text-center">
            <p><a href="http://zhangxiaoyang.farbox.com" target="_blank">Author's Blog</a> |  
                Thank <a href="http://weibo.com/316860006" target="_blank">wangxiaomo</a> | 
                <a id="btnsource" href="#">Open Source</a>
                <script src="http://s4.cnzz.com/stat.php?id=5435844&web_id=5435844&show=pic1" language="JavaScript"></script>
            </p>
        </div>
    </footer>
    <!-- BEGIN PLUGINS -->
    <script src="/static/js/jquery-1.8.3.min.js" type="text/javascript"></script>		
    <script src="/static/js/jquery.cookie.js" type="text/javascript"></script>		
    <script src="/static/css/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>    
    <script type="text/javascript" src="/static/js/jquery.uploadify.js"></script>
    <script type="text/javascript" src="http://api.map.baidu.com/api?v=1.5&ak=D8d3f29f743c4526cd4408788c39640b"></script>
    <script type="text/javascript" src="http://api.map.baidu.com/library/TextIconOverlay/1.2/src/TextIconOverlay_min.js"></script>
    <script type="text/javascript" src="http://api.map.baidu.com/library/MarkerClusterer/1.2/src/MarkerClusterer_min.js"></script>
    <script type="text/javascript" src="http://api.map.baidu.com/library/SearchInfoWindow/1.5/src/SearchInfoWindow_min.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>  

    <!-- END PLUGINS -->
    <script type = "text/javascript" >
    $("#btnsource").click(function(){
      if(window.confirm('您可以使用代码中的任何语句, 请注明出处, 严禁用于商业用途, 确定吗?')){
          window.open("https://github.com/zhangxiaoyang/classmate", "_blank"); 
      }
    });
    $.getJSON("/ajax/querylogin", {"classid":$("#current").text()},function(data){
        $("#current").text(data).show();
    });
    </script>
    {% block js %}{% endblock %}
</body>
<!-- END BODY -->
</html>

templates/change_student.html
{% extends "base.html" %}
{% block page %}
<!-- Weixin help
================================================== -->
<div id="dlgweixin" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 id="dlgtitle">使用帮助</h3>
    </div>
    <div class="modal-body">
        <div class="row-fluid">
            <div class="span4"></div>
            <img class="span4" src="http://bcs.duapp.com/mediaavatar/code.jpg"> 
            <div class="span4"></div>
        </div>
        <div class="row-fluid">
            <ul style="list-style-type:none;text-indent: 2em;">
                <li>执行完以下操作后，您可以使用微信随时随地更新、查询信息~</li><br/>
                <li>Step 1. 用微信扫描以上二维码</li>
                <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;（或者用微信添加公共平台: daxuetongchang）</li>
                <li>Step 2. 关注成功后，发送任意消息到大学同窗</li>
                <li>Step 3. 大学同窗会回复您的OpenID（有字、数字、乱七八糟的字符）</li>
                <li>Step 4. 把OpenID填在这里即可</li>
                <li>Step 5. 提交本页面后, 登录手机微信, 发送help到大学同窗了解手机指令</li>
            </ul>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-primary" data-dismiss="modal">看明白了</button>
    </div>
</div>

<!-- Map layer
================================================== -->
<div class="hide" id="map"></div>
<div id="dlgmap" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 id="dlgtitle">选择位置</h3>
    </div>
    <div class="modal-body">
        <div class="row-fluid">
            <label class="control-label">输入位置关键词</label>
            <div class="controls">
                <input type="text" id="txtsearch" class="span12" placeholder="示例: 北京 故宫 东门">
            </div>
        </div>
        <div class="row">
            <div id="divmap"></div>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal">取消</button>
        <button class="btn btn-primary">确定</button>
    </div>
</div>

<h1 class="form-signin-heading">修改成员</h1>
<form action="" method="POST" class="horizontal-form">{% csrf_token %}
    <!-- person info
    ================================================== -->
    <h3 class="form-section">个人信息</h3>
    <div class="row-fluid">
        <div class="span6 ">
            {% if form.studentnum.errors %}
            <div class="control-group error">
            {% else %}
            <div class="control-group">
            {% endif %}
                <label class="control-label">学号 <span class="badge badge-warning">必填</span></label>
                {{ form.studentnum }}
            </div>
        </div>
        <!--/span-->
        <div class="span6">
            {% if form.name.errors %}
            <div class="control-group error">
            {% else %}
            <div class="control-group">
            {% endif %}
                <label class="control-label">姓名 <span class="badge badge-warning">必填</span></label>
                {{ form.name }}
            </div>
        </div>
        <!--/span-->
    </div>
    <div class="row-fluid">
        <div class="span6 ">
            {% if form.qq.errors %}
            <div class="control-group error">
            {% else %}
            <div class="control-group">
            {% endif %}
                <label class="control-label">QQ</label>
                {{ form.qq }}
            </div>
        </div>
        <!--/span-->
        <div class="span6 ">
            {% if form.weibo.errors %}
            <div class="control-group error">
            {% else %}
            <div class="control-group">
            {% endif %}
                <label class="control-label">新浪微博号</label>
                {{ form.weibo }}
            </div>
        </div>
        <!--/span-->
    </div>
    <div class="row-fluid">
        <div class="span6 ">
            {% if form.phone.errors %}
            <div class="control-group error">
            {% else %}
            <div class="control-group">
            {% endif %}
                <label class="control-label">手机号码</label>
                {{ form.phone }}
            </div>
        </div>
        <!--/span-->
        <div class="span6">
            {% if form.mail.errors %}
            <div class="control-group error">
            {% else %}
            <div class="control-group">
            {% endif %}
                <label class="control-label">E-mail</label>
                {{ form.mail }}
            </div>
        </div>
        <!--/span-->
    </div>
    <div class="row-fluid">
        <div class="span6 ">
            {% if form.birthday.errors %}
            <div class="control-group error">
            {% else %}
            <div class="control-group">
            {% endif %}
                <label class="control-label span2">生日
                </label>
                <ul>
                  <li class="span2" style="list-style-type:none"><label class="radio"><input id="g" type="radio" name="rddate" value="公历" checked="checked">公历</label></li>
                  <li class="span2" style="list-style-type:none"><label class="radio"><input id="n" type="radio" name="rddate" value="农历">农历</label></li>
                </ul>
                {{ form.birthday }}
            </div>
        </div>
        <!--/span-->
        <div class="span6 ">
            {% if form.position.errors %}
            <div class="control-group error">
            {% else %}
            <div class="control-group">
            {% endif %}
                <label class="control-label">当前位置 <span class="badge badge-warning">必填</span></label>
                {{ form.position }}
            </div>
        </div>
        <!--/span-->
    </div>
    <div class="row-fluid">
        <div class="span6 ">
            {% if form.weixin.errors %}
            <div class="control-group error">
            {% else %}
            <div class="control-group">
            {% endif %}
                <label class="control-label">微信OpenID(不是微信号)<a href="#" id="btnweixin">不是微信号，点我一下看看究竟</a></label>
                {{ form.weixin }}
            </div>
        </div>
        <!--/span-->
    </div>
    <div class="row-fluid">       
        <input id="btnupload" name="avatar" type="file">        
        <img id="id_avatar" onerror='this.src="http://bcs.duapp.com/mediaavatar/error.jpg";' src="http://bcs.duapp.com/mediaavatar/{{studentid}}.jpg" style="height:70px;width:70px">
        <!--/span-->
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-primary">确定</button>
        <a type="button" href="/" class="btn">取消</a>
    </div>
</form>
{% endblock %}

{% block js %}
<script type = "text/javascript" >
// function showPreview(coords) {
//     if (parseInt(coords.w) > 0) {
//         //计算预览区域图片缩放的比例，通过计算显示区域的宽度(与高度)与剪裁的宽度(与高度)之比得到
//         var rx = $("#preview_box").width() / coords.w;
//         var ry = $("#preview_box").height() / coords.h;
//         //通过比例值控制图片的样式与显示
//         $("#crop_preview").css({
//             width: Math.round(rx * $("#xuwanting").width()) + "px", //预览图片宽度为计算比例值与原图片宽度的乘积
//             height: Math.round(rx * $("#xuwanting").height()) + "px", //预览图片高度为计算比例值与原图片高度的乘积
//             marginLeft: "-" + Math.round(rx * coords.x) + "px",
//             marginTop: "-" + Math.round(ry * coords.y) + "px"
//         });
//     }
//}
// 日期控件
$("input:radio").click(function(){
    var rddate = $(this).attr("id");
    $("#id_birthday").val(rddate+$("#id_birthday").val().replace(/[^0-9]/ig,""));
});
$("#id_birthday").datepicker({
    defaultDate:new Date(1990, 01, 01), 
    'dateFormat':('yymmdd'),
    onSelect: function(date) {
        if($("#g").attr("checked") == "checked"){
            $("#id_birthday").val("g"+$("#id_birthday").val().replace(/[^0-9]/ig,""));
        }else if($("#n").attr("checked") == "checked"){
            $("#id_birthday").val("n"+$("#id_birthday").val().replace(/[^0-9]/ig,""));
        }
    }
});
  
$('#id_avatar').error(function(){
    $(this).hide();
});
$('#btnupload').uploadify({　　
    'formData' : { 'csrfmiddlewaretoken' : '{{ csrf_token }}'},
    'swf': '/static/swf/uploadify.swf',
    'uploader'  : '/ajax/upload/{{studentid}}/',
    'buttonText': '上传头像',
    'fileTypeExts': '*.jpg;*.bmp;*.png;*.gif',
    'onUploadSuccess' : function (file, data, response) {
      $('#id_avatar').show();
      $("#id_avatar").attr('src', 'http://bcs.duapp.com/mediaavatar/{{studentid}}.jpg?timestemp='+new Date().getTime());
        // $('#id_avatar').Jcrop({
        //     onChange:showPreview,
        //     onSelect:showPreview,
        //     aspectRatio:1
        // });
    }
});
$("#btnweixin").click(function(){
    $("#dlgweixin").modal('show');
});
$("#id_position").click(function(){
    $("#dlgmap").modal('show');
});

var map = new BMap.Map("map");// 创建Map实例
$("#txtsearch").keyup(function(){

map.centerAndZoom(new BMap.Point(116.404, 39.915), 11)
    var options = {
        onSearchComplete: function(results) {
            // 判断状态是否正确
            if (local.getStatus() == BMAP_STATUS_SUCCESS) {
                var s = "<ul>";
                for (var i = 0; i < results.getCurrentNumPois(); i++) {
                    s += '<li class="span12">';
                    s += '<a href="#" class="lbladdress">';
                    s += results.getPoi(i).title + "," + results.getPoi(i).address;
                    s += '('+results.getPoi(i).point.lng + ','+ results.getPoi(i).point.lat+')';
                }
                s += "</ul>"
                $("#divmap").html(s);

                $(".lbladdress").click(function(){
                    $("#dlgmap").modal('hide');
                    $("#id_position").val($(this).text());
                });
            }
        }   
    };
    var local = new BMap.LocalSearch(map, options);
    local.setPageCapacity(15);
    local.search($(this).val());
});
</script>
{% endblock %}